version: 0.0
os: linux

files:
  - source: /pulse-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/pulse

permissions:
  - object: /home/ec2-user/pulse
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: ec2-user

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: ec2-user

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 120
      runas: ec2-user
